server:
  port: 9010

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ctc_customer?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource